export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const ADD_DOCUMENTS = 'ADD_DOCUMENTS';
export const DOCUMENTS_LOADED = 'DOCUMENTS_LOADED';
export const SHAREPOINT_CONNECT_ERROR = 'SHAREPOINT_CONNECT_ERROR';
export const FILTER_DOCUMENTS_BY_NAME = 'FILTER_DOCUMENTS_BY_NAME';
