export const DOCUMENTS_LOADED = 'DOCUMENTS_LOADED';
export const START_LOAD_DOCUMENTS = 'START_LOAD_DOCUMENTS';
export const SHAREPOINT_CONNECT_ERROR = 'SHAREPOINT_CONNECT_ERROR';
export const FILTER_DOCUMENTS_BY_NAME = 'FILTER_DOCUMENTS_BY_NAME';
